# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'HONG-TED'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'HONG and TED',  url: 'facts'}
- {name: 'Stories', url: 'resources'}
- {name: 'Ideas', url: 'sample-posts'}
- {name: 'Conversations', url: 'documentation'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link:   'https://www.instagram.com/redynag?igsh=MWVsdDAwZW9obnBpYg%3D%3D&utm_source=qr'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'HONG-TED'

related_posts: 'HONG and Ted '

post_date_prefix: 'Endless boundaries'
